//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newWPF.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalsTable
    {
        public string Id { get; set; }
        public string KindOfAnimal { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }

        public AnimalsTable(string name, string age, string gender)
        {
            Name = name;
            Age = age;
            Gender = gender;
        }
        public AnimalsTable() { }
    }
}
